spring.application.name=FlashMark

# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/flashmark
spring.datasource.username=root
spring.datasource.password=S1090274779o
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect